services:
  - type: web
    name: spring-boot-api
    env: docker
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: docker build -t spring-boot-api . && docker run spring-boot-api
